on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.57.2
          TARGET_REPO: pkanwar23/pkanwar23.github.io
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: deploy
      #  run: |
      #    shellcheck *.sh
      #  env:
      #    HUGO_VERSION: 0.59.1
      #    TARGET_REPO: pkanwar23/pkanwar23.github.io
      #    PUSH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
